blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('search/<str:ct>/<str:q>/', views.PostSearch.as_view(), name="search"),
    path('delete_comment/<int:pk>/', views.delete_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('delete_post/<int:pk>/', views.delete_post),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('create_post/', views.PostCreate.as_view(), name="create"),
    path('tag/<str:slug>/', views.tag_page),
    path('category/<str:slug>/', views.category_page),
    path('<int:pk>/new_comment/', views.new_comment),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('membership_page/', views.membership_page, name="membership_page"),
    path('', views.PostList.as_view(), name="news"),

]

board/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('delete_board/<int:pk>/', views.BoardDelete.as_view()),
    path('update_board/<int:pk>/', views.BoardUpdate.as_view()),
    path('create/', views.BoardCreate.as_view(), name="board_create"),
    path('<int:pk>/', views.BoardDetail.as_view()),
    path('', views.BoardList.as_view(), name="boardList"),
]

do_it_django_prj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

handler404 = 'blog.views.error_404_view'
handler500 = 'blog.views.error_500_view'

urlpatterns = [
    path('board/', include('board.urls')),
    path('single/', include('single_pages.urls')),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('blog.urls')),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

board/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'[{self.pk}]{self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'/board/{self.pk}/'

board/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget

from board.models import Board


class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['title', 'content']
        widgets = {
            'content': SummernoteWidget(),
        }

board/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from board.forms import BoardForm
from board.models import Board


class BoardList(ListView):
    model = Board
    ordering = '-pk'


class BoardDetail(DetailView):
    model = Board


class BoardCreate(LoginRequiredMixin, CreateView):
    model = Board
    form_class = BoardForm

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            response = super(BoardCreate, self).form_valid(form)

            return response
        else:
            return redirect('/board/')


class BoardUpdate(LoginRequiredMixin, UpdateView):
    model = Board
    form_class = BoardForm
    template_name = 'board/board_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(BoardUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


class BoardDelete(DeleteView):
    model = Board
    context_object_name = 'target_board'
    success_url = reverse_lazy('boardList')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_superuser:
            return super(BoardDelete, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

board/templates/board/board_detail.html
{% extends 'board/board_list.html' %}
{% load static %}

{% block main_area %}

  <div class="card">
    <div class="card-body">
       <!-- Edit post -->
      {% if user.is_authenticated and user == board.author %}
      <div class="d-grid gap-2 d-md-block float-end">
        <a class="btn btn-info btn-sm" style="text-decoration: none;" href="/board/update_board/{{ board.pk }}/" role="button">수정</a>
        <a class="btn btn-danger btn-sm" style="text-decoration: none;" href="/board/delete_board/{{ board.pk }}/" role="button">삭제</a>
      </div>
      {% endif %}
      <h5 class="card-title">{{ board.title }}</h5>

      <h6 class="card-subtitle mb-2 text-muted">{{ board.author }}</h6>
      <div class="text-end">{{ board.created_at }}</div>

      <hr/>
      {{ board.content | safe }}
    </div>
  </div>

{% endblock %}

board/templates/board/board_form.html
{% extends 'board/board_list.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block main_area %}

 <h1>자유게시판</h1>
  <hr/>

  <form method="post" enctype="multipart/form-data">{% csrf_token %}
      <table>
          {{ form | crispy }}
      </table>
    <button type="submit" class="btn btn-primary float-end mt-3">제출하기</button>
  </form>


{% endblock %}

board/templates/board/board_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container px-5">
    <div class="row gx-5 justify-content-left">
        <div class="col-lg">
            <div class="text-center my-5">
                <h1 class="display-5 fw-bolder my-3">게시판</h1>
                <p>미라클레터에 대해 자유롭게 작성해주세요.</p>
            </div>
        </div>
    </div>
</div>

  <div class="container my-3">
      <div class="row">
        <div class="col" id="main-area">
          {% block main_area %}
            <div class="table-responsive-md">
              <table class="table mt-5" >
                  <thead>
                    <tr class="py-3" >
                      <th scope="col">#</th>
                      <th scope="col">제목</th>
                      <th scope="col">작성자</th>
                      <th scope="col">작성일</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for board in board_list %}
                    <tr>
                      <th scope="row">{{ board.pk }}</th>
                      <td class="col-5"><a class="text-decoration-none" href="{{ board.get_absolute_url }}" style="color:black;">{{ board.title }}</a></td>
                      <td>{{ board.author }}</td>
                      <td class="col-3">{{ board.created_at }}</td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
            </div>

            {% if request.user.is_authenticated %}
              <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <a href="{% url 'board_create' %}" type="button" class="btn btn-secondary float-end">글쓰기</a>
              </div>
            {% else %}
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <a href="{% url 'login' %}" type="button" class="btn btn-secondary float-end">글쓰기</a>
                </div>
            {% endif %}
          {% endblock %}
        </div>
      </div>
      <!-- /.row -->

</div>
{% endblock %}

board/templates/board/board_update_form.html
{% extends 'board/board_list.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block main_area %}

 <h1>게시물 수정</h1>
  <hr/>

  <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
          {{ form | crispy }}
      </table>
    <button type="submit" class="btn btn-primary float-end">Submit</button>
  </form>


{% endblock %}